

# change the prefix binding to control-a and unbind the default
# this works great when remapping caps-lock to ctrl.
set-option -g prefix C-a
unbind C-b

# unbind and rebind r to reload the config
unbind R
bind R source-file ~/.config/tmux/tmux.conf

########
# personal prefs
########

# act like vim to select windows
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# sensible numbering on windows and panes
set-option -g base-index 1

# convenience bindings
bind-key p paste-buffer
bind-key P choose-buffer
bind-key Escape copy-mode
bind-key Enter new-window


set -g mouse on

########
# plugins
########
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# this plugin allows you to quickly switch between
# vim windows with ctl - h/j/k/l
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# eyecandy
set -g default-terminal "screen-256color"
set -g allow-passthrough on
set -ga terminal-overrides ",*256col*:Tc"
#set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

set -g @nord_tmux_no_patched_font "1"
set -g @plugin 'nordtheme/tmux'


# bootstrap tpm on a new machine
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# initialise TMUX plugin manager - NB keep at bottom
run '~/.config/tmux/plugins/tpm/tpm'

# notes:
# prefix I - install plugins

