" Basic Vim setup
"
" This must be first, because it changes other options as a side effect.
set nocompatible

set hidden

" Set 256 Colours

set t_Co=256

" Load pathogen.vim
" execute pathogen#infect()
if v:version >= 700
    try
        runtime pathogen/autoload/pathogen.vim
        call pathogen#infect()
    catch
    endtry
endif

" Enable Syntax Hilighting
syntax on

" Check files for VIM mode setting lines
set modeline

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set colorcolumn=80

filetype plugin on
filetype indent on

" ================ Colorscheme ======================
let base16colorspace=256  " Access colors present in 256 colorspace
set background=dark
colorscheme base16-default

" ================ Syntastict Settings ======================
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


" ================  Prompt line setup ======================
" Dont use powerline font symbols
let g:promptline_powerline_symbols = 1
"let g:promptline_symbols = {
"      \ 'left'           : '',
"      \ 'right'          : '',
"      \ 'left_alt'       : '>',
"      \ 'right_alt'      : '<',
"      \ 'dir_sep'        : '/',
"      \ 'truncation'     : '...',
"      \ 'vcs_branch'     : '⚭',
"      \ 'battery'        : '',
"      \ 'space'          : ' '}

let g:promptline_theme = 'airline'

let g:promptline_preset = {
    \'a' : [ '\u@\h' ],
    \'b' : [ promptline#slices#cwd({ 'dir_limit': 8 }) ],
    \'y' : [ promptline#slices#vcs_branch({ 'hg': 0, 'svn': 1, 'fossil': 0}) ],
    \'warn' : [ promptline#slices#last_exit_code() ]}

" ================  Vim airline setup ======================

let g:airline#extensions#tmuxline#enabled = 1
let g:airline#extensions#promptline#enabled = 0
let g:airline#extensions#promptline#snapshot_file = "~/code/dotfiles/shellrc/rc.d/prompt/01_prompt.bash"


" ================  Vim airline setup ======================
if executable("ag")
      let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""'
endif

" ================  Vim Filetype Overides ======================
au BufNewFile,BufRead *.jca set filetype=xml
au BufNewFile,BufRead *.jpr set filetype=xml
au BufNewFile,BufRead *.jws set filetype=xml
