[skin]
    description = Nord

[aliases]

# standard colors
# 00 black, 01 red, 02 green, 03 yellow (brown), 04 blue, 05 magenta, 06 cyan
# 07 white, 08 gray,  09 brightred, 10 brightgreen, 11 yellow, 12 brightblue, 
# 13 brightmagenta, 14 brightcyan, 15 white
# 16 lightgray
nord0=black
nord3=gray
nord4=lightgray
nord5=white
nord7=brightcyan
nord8=brightblue
nord9=cyan
nord10=blue
nord11=red
nord12=brown
nord13=yellow
nord14=green
nord15=magenta

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ─
    dvert = │
    dlefttop = ┌
    drighttop = ┐
    dleftbottom = └
    drightbottom = ┘
    dtopmiddle = ┬
    dbottommiddle = ┴
    dleftmiddle = ├
    drightmiddle = ┤

[core]
    _default_ = nord4;nord0
    selected = nord4;nord10
    marked = nord13;nord0
    markselect = nord13;nord10
    gauge = nord3;nord8
    input = nord13;nord0
    inputunchanged = nord11;nord0
    inputmark = black;lightgray
    disabled = gray;black
    reverse = brown;black
    commandlinemark = nord11;nord0
    header = nord14;nord0
    inputhistory =
    commandhistory =
    shadow = gray;black

[dialog]
    _default_ = nord4;nord3
    dfocus = nord7;nord3
    dhotnormal = nord13;nord3
    dhotfocus = nord14;nord3
    dtitle = nord13;nord3

[error]
    _default_ = nord11;nord3
    errdfocus = nord13;nord3
    errdhotnormal = nord4;nord3
    errdhotfocus = nord11;nord3
    errdtitle = nord13;nord3

[menu]
    _default_ = nord4;nord3
    menusel = lightgray;nord10
    menuhot = nord13;nord3
    menuhotsel = nord13;nord10
    menuinactive = nord9;nord3

[popupmenu]
    _default_ = lightgray;black
    menusel = lightgray;blue
    menutitle = lightgray;black

[buttonbar]
    hotkey = nord13;nord0
    button = nord9;nord0

[statusbar]
    _default_ = nord11;nord0

[help]
    _default_ = lightgray;black
    helpitalic = red;black
    helpbold = brown;black
    helplink = blue;black
    helpslink = lightgray;blue
    helptitle = brown;black


[filehighlight]
    directory = blue;
    executable = brightgreen;
    symlink = gray;
    hardlink =
    stalelink = brightred;
    device = brightmagenta;
    special = gray;
    core = red;
    temp = gray;
    archive = magenta;
    doc = lightgray;
    source = brightcyan;
    media = green;
    graph = cyan;
    database = brightred;

[editor]
    _default_ = lightgray;black
    editbold = brown;blue
    editmarked = black;cyan
    editwhitespace = brightblue;blue
    editnonprintable = ;black
    editlinestate = white;cyan
    bookmark = white;red
    bookmarkfound = black;green
    editrightmargin = brightblue;black
#    editbg =
    editframe = gray;
    editframeactive = lightgray;
    editframedrag = brightblue;

[viewer]
    _default_ = lightgray;black
    viewbold = brown;blue
    viewunderline = brightred;blue
    viewselected = brown;cyan

[diffviewer]
    added = white;brown
    changedline = blue;cyan
    changednew = red;cyan
    changed = white;cyan
    removed = white;red
    error = red;lightgray

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = •
    hiddenfiles-hide-char = ○
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
