

# change the prefix binding to control-a and unbind the default
# this works great when remapping caps-lock to ctrl.
set-option -g prefix C-a
unbind C-b

# unbind and rebind r to reload the config
unbind R
bind R source-file ~/.tmux.conf

########
# personal prefs
########

# act like vim to select windows
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# sensible numbering on windows and panes
set-option -g base-index 1

# convenience bindings
bind-key p paste-buffer
bind-key P choose-buffer
bind-key Escape copy-mode
bind-key Enter new-window


set -g mouse on

########
# plugins
########
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# this plugin allows you to quickly switch between
# vim windows with ctl - h/j/k/l
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# eyecandy
set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

set -g @catppuccin_flavor 'macchiato-custom' # latte, frappe, macchiato or mocha
#set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_pane_status_enabled "no"

set -g @catppuccin_status_background "#242424"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

set -g status-left ""
set -g  status-right "#{E:@catppuccin_status_directory}"
#set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g status-position top

set -g @plugin 'catppuccin/tmux'

# bootstrap tpm on a new machine
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# initialise TMUX plugin manager - NB keep at bottom
run '~/.tmux/plugins/tpm/tpm'

# notes:
# prefix I - install plugins

