#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
[calendars]
default-calendars = ["cmulder@redhat.com"]
#ignore-calendars = ["Boring stuff", "Holidays"]

[output]
week-start = "monday"
